#!/usr/bin/env python3
"""CFN monthly refresh.

Triggered by launchd job `com.butters.cfn-monthly-refresh` every Monday at 9am
local. Self-gates to first Monday of each month so the actual run is monthly.

What it does:
  1. Pulls fresh Substack data via sync_jai_substack.py with the CFN publication
  2. Runs cfn_attribution_map.py to regenerate the attribution map
  3. Compares current headline metrics to the last persisted state
  4. If material thresholds crossed, writes a delta file in the signal-noise folder
     and tells Max via Telegram to run the comprehensive-report prompt
  5. Saves new state and notifies Max either way

Run with --force to bypass the first-Monday gate (useful for testing).
"""
from __future__ import annotations

import json
import subprocess
import sys
import traceback
from datetime import date
from pathlib import Path

ROOT = Path.home() / "Desktop" / "Jay Article Writer"
SNAP_DIR = ROOT / "data" / "substack_snapshots"
ADMIN_PATH = SNAP_DIR / "latest_www_signalovernoise_ai_admin_posts.json"
SUB_SUMMARY_PATH = SNAP_DIR / "latest_www_signalovernoise_ai_subscriber_summary.json"
ATTRIBUTION_MD = SNAP_DIR / "cfn_attribution_map.md"
STATE = SNAP_DIR / ".cfn-monthly-state.json"
SIGNAL_DIR = Path.home() / "Desktop" / "mb-brain" / "4 - Content" / "signal-noise"
PROMPT_FILE = (
    Path.home()
    / "Desktop" / "mb-brain" / "0 - System" / "Prompts"
    / "cfn-marketing-report-prompt.md"
)
NOTIFY = Path.home() / "Desktop" / "max-command-center" / "butters" / "scripts" / "notify.sh"
PYTHON = "/opt/homebrew/bin/python3"

# Material-change thresholds. Crossed → write delta file + notify Max to refresh
# the comprehensive report. Tune as the publication grows.
MATERIAL = {
    "min_new_posts": 4,
    "min_new_paid": 10,
    "min_new_revenue": 1000,
}


def is_first_monday() -> bool:
    today = date.today()
    return today.weekday() == 0 and today.day <= 7


def notify(msg: str) -> None:
    if NOTIFY.exists():
        try:
            subprocess.run([str(NOTIFY), msg], check=False, timeout=15)
        except Exception:
            pass
    print(f"[notify] {msg}", flush=True)


def run_step(label: str, cmd: list[str]) -> None:
    print(f"$ {' '.join(cmd)}", flush=True)
    try:
        subprocess.run(cmd, check=True, cwd=ROOT)
    except subprocess.CalledProcessError as e:
        notify(
            f"❌ CFN monthly refresh — {label} failed (exit {e.returncode}). "
            f"Most likely Chrome cookies are stale or Substack auth dropped. "
            f"Open Chrome, log into substack.com, then run --force."
        )
        sys.exit(2)


def load_metrics() -> dict:
    posts = json.loads(ADMIN_PATH.read_text())
    sub_summary = json.loads(SUB_SUMMARY_PATH.read_text())

    chart = sub_summary.get("chart_counts") or {}
    paid_count = int(chart.get("subscribers") or 0)
    total_email = int(chart.get("totalEmail") or 0)

    newsletter = [p for p in posts if p.get("type") == "newsletter" and (p.get("opened") or 0) > 0]
    total_paid_attributed = sum(int(p.get("subscribes") or 0) for p in newsletter)
    total_revenue = sum(float(p.get("estimated_value") or 0) for p in newsletter)
    post_count = len(newsletter)

    return {
        "date": date.today().isoformat(),
        "paid_count": paid_count,
        "total_email": total_email,
        "total_paid_attributed": total_paid_attributed,
        "total_revenue": int(total_revenue),
        "post_count": post_count,
    }


def load_prior_state() -> dict:
    if STATE.exists():
        try:
            return json.loads(STATE.read_text())
        except Exception:
            return {}
    return {}


def is_material(prior: dict, current: dict) -> tuple[bool, dict]:
    if not prior:
        return True, {"reason": "first_run"}
    delta = {
        "posts": current["post_count"] - prior.get("post_count", 0),
        "paid": current["paid_count"] - prior.get("paid_count", 0),
        "revenue": current["total_revenue"] - prior.get("total_revenue", 0),
    }
    triggers = []
    if delta["posts"] >= MATERIAL["min_new_posts"]:
        triggers.append(f"+{delta['posts']} posts")
    if delta["paid"] >= MATERIAL["min_new_paid"]:
        triggers.append(f"+{delta['paid']} paid subs")
    if delta["revenue"] >= MATERIAL["min_new_revenue"]:
        triggers.append(f"+${delta['revenue']:,} revenue")
    return bool(triggers), {"deltas": delta, "triggers": triggers}


def write_delta_file(prior: dict, current: dict, decision: dict) -> Path:
    out = SIGNAL_DIR / f"cfn-monthly-delta-{current['date']}.md"
    triggers = decision.get("triggers") or []
    lines = [
        f"# CFN Monthly Delta — {current['date']}",
        "",
        f"_Auto-generated by `cfn-monthly-refresh.py`. Material thresholds crossed: {', '.join(triggers) or 'first run'}._",
        "",
        f"_Prior state: {prior.get('date', 'no prior state')}._",
        "",
        "## Headline numbers",
        "",
        "| Metric | Prior | Current | Delta |",
        "|---|---|---|---|",
        f"| Paid subscribers | {prior.get('paid_count', '—')} | {current['paid_count']} | {current['paid_count'] - prior.get('paid_count', current['paid_count']):+d} |",
        f"| Total email list | {prior.get('total_email', '—')} | {current['total_email']} | {current['total_email'] - prior.get('total_email', current['total_email']):+d} |",
        f"| Newsletter posts (with opens) | {prior.get('post_count', '—')} | {current['post_count']} | {current['post_count'] - prior.get('post_count', current['post_count']):+d} |",
        f"| Total post-attributed paid (`subscribes`) | {prior.get('total_paid_attributed', '—')} | {current['total_paid_attributed']} | {current['total_paid_attributed'] - prior.get('total_paid_attributed', current['total_paid_attributed']):+d} |",
        f"| Total post-attributed revenue (`estimated_value`) | ${prior.get('total_revenue', 0):,} | ${current['total_revenue']:,} | ${current['total_revenue'] - prior.get('total_revenue', current['total_revenue']):+,} |",
        "",
        "## Next step",
        "",
        "Material change. To refresh the comprehensive marketing report, paste this prompt into a fresh Claude Code session:",
        "",
        f"`{PROMPT_FILE}`",
        "",
        "## Reference",
        "",
        f"- Latest attribution map: `{ATTRIBUTION_MD}`",
        f"- Prior comprehensive report: most recent in `{SIGNAL_DIR}/marketing-report-*.md`",
        "",
        "_This delta file does not supersede the comprehensive report. It surfaces the signal so Max can decide whether to refresh._",
    ]
    out.write_text("\n".join(lines))
    return out


def main(argv: list[str]) -> int:
    force = "--force" in argv
    if not force and not is_first_monday():
        print(f"{date.today()} is not the first Monday of the month. Exiting cleanly.")
        return 0

    notify(f"🔄 CFN monthly refresh started ({date.today().isoformat()}).")

    # Step 1 + 2: sync + analyze. Either failure is loud + non-zero exit.
    run_step(
        "Substack sync",
        [
            PYTHON,
            str(ROOT / "tools" / "sync_jai_substack.py"),
            "--publication", "www.signalovernoise.ai",
            "--chrome-profile", "Default",
            "--sync-subscribers", "--sync-admin-posts",
            "--full-subscriber-snapshot", "--limit", "50",
        ],
    )
    run_step(
        "Attribution analysis",
        [PYTHON, str(ROOT / "tools" / "cfn_attribution_map.py")],
    )

    # Step 3: compute current metrics + load prior
    current = load_metrics()
    prior = load_prior_state()
    material, decision = is_material(prior, current)

    # Step 4: assemble notification
    msg_lines = [
        f"📊 CFN monthly refresh ({current['date']})",
        f"Paid subscribers: {current['paid_count']}"
        + (f" ({current['paid_count'] - prior.get('paid_count', current['paid_count']):+d})" if prior else ""),
        f"Newsletter posts (with opens): {current['post_count']}"
        + (f" ({current['post_count'] - prior.get('post_count', current['post_count']):+d})" if prior else ""),
        f"Attributed revenue: ${current['total_revenue']:,}"
        + (f" (+${current['total_revenue'] - prior.get('total_revenue', current['total_revenue']):,})" if prior else ""),
        "",
        f"Attribution map: {ATTRIBUTION_MD}",
    ]
    if material:
        msg_lines.append("")
        triggers = decision.get("triggers") or ["first run"]
        msg_lines.append(f"⚠️ Material change ({', '.join(triggers)}).")
        delta_path = write_delta_file(prior, current, decision)
        msg_lines.append(f"Delta file: {delta_path}")
        msg_lines.append("")
        msg_lines.append(f"To refresh the comprehensive report, paste {PROMPT_FILE} into a fresh Claude Code session.")
    else:
        msg_lines.append("")
        msg_lines.append("No material change. State updated; comprehensive report not regenerated.")

    # Step 5: persist state + notify
    STATE.write_text(json.dumps(current, indent=2))
    notify("\n".join(msg_lines))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except SystemExit:
        raise
    except Exception:
        notify(f"❌ CFN monthly refresh crashed:\n{traceback.format_exc()[:1500]}")
        raise SystemExit(3)
